name: Build & Testing distribute

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run build

  Test:
    runs-on: macos-latest
    needs: Build
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        target: [ iOS, Android, Windows, macOS ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm i
          npm i -g appcenter-cli

      - uses: ./
        with:
          token: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          path: ${{ github.workspace }}/artifacts/Build.${{ fromJSON('["ipa", "aab", "zip", "pkg"]')[strategy.job-index] }}
          app: akiojin/Unity_${{ matrix.target }}
          mandatory: true
          silent: false
          group: Testers
          release_notes: |
            "# GitHub Actions
            - Action : ${{ github.event_name }}
            - Requester : ${{ github.actor }}
            - Commit Message : ${{ github.event.head_commit.message }}"
