name: Review PRs

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  Review:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: akiojin/auto-review-github-action@v1
        with:
          openai-api-key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          target: 'ts,yml'
          language: 日本語
          resource-name: ${{ secrets.AZURE_OPENAI_RESOURCE_NAME }}
          deployment-id: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_ID }}
